---
- name: Install dante-server package
  ansible.builtin.apt:
    name: dante-server
    update_cache: true
  tags: [Install]

- name: Create group {{ dante_group }}
  ansible.builtin.group:
    name: "{{ dante_group }}"
    system: true
    state: present
  tags: [Install, Configure]

- name: Create user {{ dante_user }}
  ansible.builtin.user:
    name: "{{ dante_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ dante_group }}"
    create_home: false
  tags: [Install, Configure]

- name: Create logs file
  ansible.builtin.file:
    path: "{{ dante_logs }}"
    state: file
    owner: "{{ dante_user }}"
    group: "{{ dante_group }}"
    mode: "644"
  tags: [Install, Configure]

- name: Add config
  ansible.builtin.template:
    src: danted.conf.j2
    dest: "{{ dante_config }}"
    group: "{{ dante_group }}"
    owner: "{{ dante_user }}"
    mode: "644"
  tags: [Configure]
  notify:
    - Restart dante

- name: Enable dante systemd service
  ansible.builtin.systemd:
    name: danted.service
    state: started
    enabled: true
    masked: false
  tags: [Configure]
