driver:
  name: docker

platforms:
  - name: debian12
    image: alexey1607/systemd:debian12
    privileged: true
    cgroupns_mode: host
    stop_signal: SIGRTMIN+3
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible

verifier:
  name: ansible
