---
driver:
  name: docker

platforms:
  - name: dante-debian12
    image: alexey1607/systemd:debian12
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    stop_signal: SIGRTMIN+3

provisioner:
  name: ansible

verifier:
  name: ansible
