---
- name: Verify dante installation
  hosts: all
  gather_facts: false
  tasks:

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Ensure danted.service exists
      ansible.builtin.assert:
        that:
          - "'danted.service' in ansible_facts.services"
        fail_msg: "danted.service not found"
        success_msg: "danted.service found"
