name: Molecule Test

on:
  push:
    branches: [develop]

jobs:
  molecule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Molecule tests
        run: |
          cd $GITHUB_WORKSPACE
          export MOLECULE_DEBUG=true
          molecule test

      - name: Push Ansible Galaxy Role
        uses: ansible-actions/ansible-galaxy-action@v1.2.0
        env:
          ANSIBLE_GALAXY_API_TOKEN: ${{ secrets.ANSIBLE_GALAXY_API_TOKEN }}
