name: Molecule Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  molecule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python & Ansible dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install ansible molecule[docker] docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Molecule tests
        run: |
          molecule test
